version: 2.1
jobs:
  build:
    docker:
      - image: building-on-ci
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t rpozo/python-selenium-testing:latest .
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker image
          command: docker push rpozo/python-selenium-testing:latest
