version: 2.1
jobs:
  build:
    environment:
      IMAGE_NAME: rpozo/python-selenium-testing
      TAG: latest
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t $IMAGE_NAME:$TAG .
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run:
          name: Push Docker image
          command: docker push $IMAGE_NAME:$TAG 
workflows:
  version: 2
  build-master:
    jobs:
      - build:
          filters:
            branches:
              only: master